# 本地运行配置文件
Server:
  AppMode: debug    # 环境：debug 开发环境 release 生产环境
  BackPort: :8081   # 后台服务端口
  FrontPort: :8082  # 前台服务端口

MySQL:
  Host: 127.0.0.1   # 地址
  Port: 3306        # 端口
  DataBase: btf     # 库名
  UserName: root    # 账号
  Password: root123 # 密码

Redis:
  Addr: localhost:6379 # 地址
  Password: # 密码
  DB: 11 # 库

Session:
  Name: "mySession" # 会话名
  Salt: "salt"      # 盐值
  ExpireTime: 12    # session过期时间

JWT:
  Issuer: btf       # jwt签发者
  SecretKey: 123456 # jwt密钥
  ExpireTime: 12  # jwt过期时间

Zap:
  Level: "error"        # 日志级别: debug, info, warn, error, dpanic, panic, fatal, 默认 info
  Format: "console"     # 输出格式: console, json
  Prefix: "[BTF] "      # 日志前缀
  Directory: "log"      # 存放日志的文件夹
  ShowLine: true        # 是否显示哪行调用
  LogInConsole: true    # 是否输出到控制台